### ISSUE TITLE
Support listening interface config in HttpConf

### ISSUE THREAD

**Issue by drewrobb** [mesosphere/chaos#13]
It would be nice to have a command line option for this, for example, to listen on localhost only instead of 0.0.0.0. Jetty supports this via: http://download.eclipse.org/jetty/8.1.15.v20140411/apidocs/org/eclipse/jetty/server/Server.html#Server(java.net.InetSocketAddress)

**Comment by kolloch** [comment]
That should be supported via --http_address or do you mean for https?
