### ISSUE TITLE
Secure command line flags should be configurable via environment variables

### ISSUE THREAD

**Issue by swartzrock** [mesosphere/chaos#27]
It should be possible to set the --http_credentials, --ssl_keystore_password and --ssl_keystore_path secure flags via environment variables. There is a security issue with passing them in via command line flags as their values will be visible in the process list.

**Comment by kolloch** [comment]
That was fixed. Or is anything missing? @swartzrock

**Comment by swartzrock** [comment]
Yup fixed, thanks
